* Ultimate Skewb
The ultimate skewb is a permutation puzzle. We will analyse it with gap.
Ultimately we would like to know the structure of the group. In order to answer
that question, we will develop the necessary theory.

** Chain of Subgroups
The entire group is generated by a number of generators. We can make a chain of
subgroups by focusing on fewer generators at a time. Let start with One
generator.


** Subgroup
We will focus our attention first on a subgroup of the ultimate skewb. In
particular the subgroup generated by the left and right rotations. This group
acts on the position of the big pieces.

#+BEGIN_SRC gap :tangle yes
lpbp := (1,2,3);
rpbp := (1,3,4);

gpbp := Group([lpbp, rpbp]);
#+END_SRC 

If we introduce a little bit more resolution in our permutation representation
we can define an action on the faces of the big pieces.

#+BEGIN_SRC gap :tangle yes
lfbp := (1,2,3)(4,5,6);
rfbp := (1,6,7)(4,3,8);

gfbp := Group([lfbp,rfbp]);
#+END_SRC

This actions has a non-trivial block system corresponding with the big pieces.

#+BEGIN_SRC gap :tangle yes
bs := Blocks(gfbp, [1..8]);
#+END_SRC

The ~gfbp~ group acts on the block system in a way that is isomorphic to the
~gpbp~ group.

#+BEGIN_SRC gap :tangle yes
hom := ActionHomomorphism(gfbp, bs, OnSets);

im := Image(hom);

iso := IsomorphismGroups(im, gfbp); 
#+END_SRC

The kernel of the homomorphism has order 2.

#+BEGIN_SRC gap :tangle yes
k := Kernel(hom);
#+END_SRC
